version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: clothing_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clothing_data
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./my-app/database_sample:/docker-entrypoint-initdb.d:ro
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
volumes:
  db_data:
