export const categoryCatalog = [
  {
    name: "T-skjorte",
    slug: "t-skjorte",
    image: "/images/category-set-v3/t-skjorte.png",
    position: "center",
    tagline: "Everyday essentials",
    artDirection: { scale: 0.95, y: 10 },
  },
  {
    name: "Genser",
    slug: "genser",
    image: "/images/category-set-v3/genser.png",
    position: "center",
    tagline: "Soft layering",
    artDirection: { scale: 0.94, y: 10 },
  },
  {
    name: "Hoodie",
    slug: "hoodie",
    image: "/images/category-set-v3/hoodie.png",
    position: "center",
    tagline: "Relaxed fit",
    artDirection: { scale: 0.95, y: 10 },
  },
  {
    name: "Skjorte",
    slug: "skjorte",
    image: "/images/category-set-v3/skjorte.png",
    position: "center",
    tagline: "Clean tailoring",
    artDirection: { scale: 0.95, y: 10 },
  },
  {
    name: "Bukse",
    slug: "bukse",
    image: "/images/category-set-v3/bukse.jpg",
    position: "center",
    tagline: "Smart comfort",
    artDirection: { scale: 0.96, y: 14 },
  },
  {
    name: "Jeans",
    slug: "jeans",
    image: "/images/category-set-v3/jeans.png",
    position: "center",
    tagline: "Denim rotation",
    artDirection: { scale: 0.98, y: 14 },
  },
  {
    name: "Shorts",
    slug: "shorts",
    image: "/images/category-set-v3/shorts.png",
    position: "center",
    tagline: "Warm weather",
    artDirection: { scale: 0.95, y: 14 },
  },
  {
    name: "Blazer",
    slug: "blazer",
    image: "/images/category-set-v3/blazer.png",
    position: "center",
    tagline: "Elevated looks",
    artDirection: { scale: 0.94, y: 10 },
  },
  {
    name: "Jakke",
    slug: "jakke",
    image: "/images/category-set-v3/jakke.png",
    position: "center",
    tagline: "Outerwear edit",
    artDirection: { scale: 0.94, y: 10 },
  },
];

export const categoryNames = categoryCatalog.map((category) => category.name);
